version: "3.6"

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.85.0
    command: --config=/etc/otelcol/config.yaml
    volumes:
      - ./collector.yaml:/etc/otelcol/config.yaml
    environment:
      - NEW_RELIC_OTLP_ENDPOINT
      - NEW_RELIC_API_KEY
    ports:
      - "4317:4317"
      - "4318:4318"

  dotnet-app:
    build: app
    environment:
      - OTEL_SERVICE_NAME=SampleDotnetApp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8080:80"
